## 

    try 块让您可以测试代码块是否有错误。 
    except 块可让您处理错误。 
    else 块允许您在没有错误的情况下执行代码。 
    finally 块允许您执行代码，而不管 try- 和 except 块的结果如何。


```python
try:
  f = open("demofile.txt")
  try:
    f.write("Lorum Ipsum")
  except:
    print("Something went wrong when writing to the file")
  finally:
    f.close()
except:
  print("Something went wrong when opening the file")
```


## raise 触发异常

```python
x = -1

if x < 0:
  raise Exception("Sorry, no numbers below zero")


x = "hello"

if not type(x) is int:
  raise TypeError("Only integers are allowed")
```

## assert 断言

```python
x = "hello"

#if condition returns False, AssertionError is raised:
assert x == "goodbye", "x should be 'hello'"


# output
Traceback (most recent call last):
  File "demo_ref_keyword_assert2.py", line 4, in <module>
    assert x == "goodbye", "x should be 'hello'"
AssertionError: x should be 'hello'
```